auto: true
title: The Trojan Eaters
description: Covers Band, North East England
contact-no: 07896 162 064
navigable-pages:
  - title: home
    url: index.html
  - title: band
    url: band.html
  - title: set
    url: set.html
  - title: gigs
    url: gigs.html
  - title: videos
    url: videos.html
  - title: photos
    url: photos.html
  - title: feedback
    url: feedback.html
  - title: contact
    url: contact.html