auto: true
title: ianreah.github.com
description: 
navigable-pages:
  - title: home
    url: /jekyll-playground/index.html
  - title: projects
    url: /jekyll-playground/projects.html
  - title: about
    url: /jekyll-playground/about.html